### ISSUE TITLE
composer install問題

### ISSUE THREAD

**Issue by crhg** [nunun/laraz#1]
起動時にcomposer installを行うかどうか決定するためにcomposer.jsonのハッシュ値を保存してチェックしていますが、以下の問題があります。

* 何らかの問題でcomposer installに失敗した場合も保存するハッシュ値が更新されるので、以後composer installがスキップされ続けてしまう。
* composr.jsonの変更なしにパッケージ側のバージョンアップなどでcomposer.lockが更新された場合に反映されない

実際にはcomposer installコマンドは既にパッケージがインストール済みならそんなに時間はかからないので更新チェックなどを自分で行わずに毎回呼んでも問題ないと思います。

**Comment by nunun** [comment]
https://github.com/nunun/laraz/commit/e3d436e6e786493ab2fcc8cdd128060359996ab6
修正しました。
docker pull してご確認下さい。
